import type { MetadataRoute } from "next";

import { BRAND_COLORS } from "@/config/brand";
import { site } from "@/config/site";

/**
 * Web app manifest: the home-screen name, colours and icons Android and
 * desktop browsers use when the site is saved or pinned.
 *
 * `minimal-ui` rather than `standalone`: this is a brand website, not an app,
 * so a saved shortcut should still offer back navigation and the URL.
 *
 * The icon files are generated by `npm run icons` from `config/brand.ts`.
 */
export default function manifest(): MetadataRoute.Manifest {
  return {
    name: site.name,
    short_name: site.shortName,
    description: site.description,
    start_url: "/",
    scope: "/",
    display: "minimal-ui",
    lang: site.locale,
    dir: "ltr",
    background_color: BRAND_COLORS.canvas,
    theme_color: BRAND_COLORS.primary,
    icons: [
      { src: "/icons/icon-192.png", sizes: "192x192", type: "image/png", purpose: "any" },
      { src: "/icons/icon-512.png", sizes: "512x512", type: "image/png", purpose: "any" },
      { src: "/icons/icon-maskable-512.png", sizes: "512x512", type: "image/png", purpose: "maskable" },
    ],
  };
}
